"""empty message

Revision ID: 884d23db27b1
Revises: c7fd43d8867d
Create Date: 2018-05-08 10:04:30.244776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884d23db27b1'
down_revision = 'c7fd43d8867d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('keyword', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'keyword')
    # ### end Alembic commands ###
